apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: {{ .Values.issuer.name }}
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ .Values.app.domain }}
    secretName: rafflethor-staging-crt
  rules:
  - host: {{ .Values.app.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.app.name }}
          servicePort: {{ .Values.app.service.port }}
