apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.port }}
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}
    tier: {{ .Values.app.tier }}
