apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      tier: {{ .Values.app.tier }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        tier: {{ .Values.app.tier }}
    spec:
      containers:
        - image: {{ .Values.app.docker.label }}:{{ .Values.app.docker.version }}
          name: {{ .Values.app.name }}
          ports:
            - containerPort: {{ .Values.app.docker.containerPort }}
