dependencies:
- name: nginx-ingress
  version: 0.19.x
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: cert-manager
  version: 0.5.x
  repository: https://kubernetes-charts.storage.googleapis.com/
