kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: travis-role-binding
  namespace: rafflethor
subjects:
- kind: ServiceAccount
  name: travis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: travis-deploy-role
